apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: staging
    db-schema: v1.4
spec:
  replicas: 3
  template:
    metadata:
      labels:
        environment: staging
